name: Python CI - Run Pytest

on:
  push:
    branches:
      - user/JorgeQuiros/feature/lab4 
  pull_request:
    branches:
      - user/JorgeQuiros/feature/lab4

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests with pytest
      run: |
        pytest
