name: CI Pipeline

on:
  push:
    branches:
      - 'user/JuanViquez/feature/lab4'  # Ejecuta el pipeline en cada push a cualquier rama
  pull_request:
    branches:
      - '*'  # Ejecuta el pipeline en cada pull request a cualquier rama

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r general_examples/tests_example/requirements.txt

    - name: Run tests
      run: |
        pytest general_examples/tests_example/tests
