name: Python CI

on:
  push:
    branches: [ main, user/andresMurillo23/feature/lab4 ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.1'

    - name: Install dependencies
      working-directory: general_examples/tests_example
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      working-directory: general_examples/tests_example
      run: |
        pytest tests
