name: Run Pytest

on:
  push:
    branches: [ main, user/isaac_zuniga/feature/lab4 ]
  pull_request:
    branches: [ main ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13.2'

      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r general_examples/tests_example/requirements.txt

      - name: Running tests with Pytest
        run: |
          pytest general_examples/tests_example/tests

